config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    if Rails.env == "production"
        request.subdomain.present?
    elsif Rails.env == "staging"
      request.subdomain.present?
    else
      request.subdomain.present?
      end
  end
end

class SubdomainBlank
  def self.matches?(request)
    if Rails.env == "production"
        request.subdomain.blank?
    elsif Rails.env == "staging"
        request.subdomain.blank?
    else
        request.subdomain.blank?
    end
  end
end

Rails.application.routes.draw do


  get 'visits/create'
  get 'visits/update'
  get 'staffs/index'
  get 'staffs/new'
  get 'staffs/show'
  get 'staffs/edit'
  post 'create_staff', to: 'staffs#create_staff'
  # devise_for :users
  # constraints(SubdomainPresent) do
  #   root 'pages#subindex', as: :subdomain_root
  # end
  constraints(SubdomainBlank) do
    root 'pages#index'
  end

    devise_for :staffs, path: 'staffs', controllers: { sessions: "staffs/sessions", registrations: 'staffs/registrations', confirmations: 'staffs/confirmations', passwords: 'staffs/passwords', unlocks: 'staffs/unlocks'}
    devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords', unlocks: 'users/unlocks'}
  resources :staffs, :path_prefix => 'my'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/edit'
  root 'pages#index'

  post 'create_visit', to: 'patients#create_visit'

  resources :patients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :hospitals

  end

end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :set_staff_id
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :lockable, :timeoutable

  enum user_type: [:receptionist, :doctor, :nurse, :pharmacist, :laboratorist, :accountant, :administrator]

  private

  def set_staff_id

  end

end

app/controllers/staffs/confirmations_controller.rb
# frozen_string_literal: true

class Staffs::ConfirmationsController < Devise::ConfirmationsController
  include Accessible

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staffs/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staffs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Accessible

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staffs/passwords_controller.rb
# frozen_string_literal: true

class Staffs::PasswordsController < Devise::PasswordsController
  include Accessible

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staffs::RegistrationsController < Devise::RegistrationsController
  include Accessible
skip_before_action :check_user, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/staffs/unlocks_controller.rb
# frozen_string_literal: true

class Staffs::UnlocksController < Devise::UnlocksController
  include Accessible

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :authenticate_staff!
  # before_action :admin_user, only: :destroy
 def new
  @staff = Staff.new
 end

  def index
    @staffs = Staff.all
  end

  def show
   @user = User.find(params[:id])
   @microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
         @user = User.find(params[:id])
  end

  def update
         @user = User.find(params[:id])
         if @user.update_without_password(user_params)
             flash[:success] = "Profile updated"
             redirect_to @user
         else
             render 'edit'
         end
  end

  def destroy
         User.find(params[:id]).destroy
         flash[:success] = "User deleted"
         redirect_to users_url
  end

  def create_staff
     @staff = Staff.new(staff_params)
     respond_to do |format|
       if @staff.save
         format.html { redirect_to staffs_index_path, notice: 'staff was successfully created.' }
       else
         format.html { render :new }
       end
     end
  end




 private
 def staff_params
     params.require(:staff).permit(:first_name, :email, :last_name, :password, :password_confirmation, :phone_number, :user_type)
 end
   # Before filters
   # Confirms a logged-in user.

   # Confirms the correct user.
   def correct_staff
       @staff = Staff.find(params[:id])
       redirect_to(root_url) unless current_staff?(@staff)
   end
   def admin_staff
      flash[:success] = "access denied."
       redirect_to(root_url) unless current_staff.administrator?
   end

end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with model: @staff, url: create_staff_path, local: true do |form| %>
<%= render 'shared/error_messages', object: @staff %>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <form>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>First Name <span class="text-danger">*</span></label>
                        <%= form.text_field :first_name, class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Last Name</label>
                        <%= form.text_field :last_name, class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Phone </label>
                        <%= form.text_field :phone_number, class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Email <span class="text-danger">*</span></label>
                        <%= form.text_field :email, class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Password</label>
                        <%= form.password_field :password, class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Confirm Password</label>
                          <%= form.password_field :password_confirmation, class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-6">

                    <div class="form-group">
                        <label>Role</label>
                        <%= form.select :user_type, Staff.user_types.keys,{},selected: form.object.user_type, id: :marital_status,class: "select" %>
                    </div>
                </div>
            </div>
            <div class="m-t-20 text-center">
                <%= form.submit "Create Employee", class: "btn btn-primary submit-btn" %>
            </div>
        </form>
    </div>
</div>







<% end %>

app/views/staffs/edit.html.erb
<h1>Staffs#edit</h1>
<p>Find me in app/views/staffs/edit.html.erb</p>

app/views/staffs/new.html.erb
<div class="content">
      <div class="row">
          <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Add Employee</h4>
          </div>
      </div>
      <%= render 'form' %>
</div>

app/views/staffs/show.html.erb
<h1>Staffs#show</h1>
<p>Find me in app/views/staffs/show.html.erb</p>