config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    if Rails.env == "production"
        request.subdomain.present?
    elsif Rails.env == "staging"
      request.subdomain.present?
    else
      request.subdomain.present?
      end
  end
end

class SubdomainBlank
  def self.matches?(request)
    if Rails.env == "production"
        request.subdomain.blank?
    elsif Rails.env == "staging"
        request.subdomain.blank?
    else
        request.subdomain.blank?
    end
  end
end

Rails.application.routes.draw do


  get 'visits/create'
  get 'visits/update'
  get 'staffs/index'
  get 'staffs/new'
  get 'staffs/show'
  get 'staffs/edit'
  post 'create_staff', to: 'staffs#create_staff'
  # devise_for :users
  # constraints(SubdomainPresent) do
  #   root 'pages#subindex', as: :subdomain_root
  # end
  constraints(SubdomainBlank) do
    root 'pages#index'
  end

    devise_for :staffs, path: 'staffs', controllers: { sessions: "staffs/sessions", registrations: 'staffs/registrations', confirmations: 'staffs/confirmations', passwords: 'staffs/passwords', unlocks: 'staffs/unlocks'}
    devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords', unlocks: 'users/unlocks'}
  resources :staffs, :path_prefix => 'my'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/edit'
  root 'pages#index'

  post 'create_visit', to: 'patients#create_visit'

  resources :patients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :hospitals

  end

end

app/views/layouts/menu/_menu.html.erb
<div class="header-left">
  <% unless @hospital.blank? %>
  <%= link_to root_path, class: "logo" do %>
    <span><%= @hospital.name %></span>
  <% end %>
  <% end %>
</div>
<a id="toggle_btn" href="javascript:void(0);"><i class="fa fa-bars"></i></a>
      <a id="mobile_btn" class="mobile_btn float-left" href="#sidebar"><i class="fa fa-bars"></i></a>
      <ul class="nav user-menu float-right">
          <li class="nav-item dropdown d-none d-sm-block">
              <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"><i class="fa fa-bell-o"></i> <span class="badge badge-pill bg-danger float-right">3</span></a>
              <div class="dropdown-menu notifications">
                  <div class="topnav-dropdown-header">
                      <span>Notifications</span>
                  </div>
                  <div class="drop-scroll">
                      <ul class="notification-list">
                          <li class="notification-message">
                              <a href="activities.html">
                                  <div class="media">
                <span class="avatar">
                  <img alt="John Doe" src="assets/img/user.jpg" class="img-fluid">
                </span>
                <div class="media-body">
                  <p class="noti-details"><span class="noti-title">John Doe</span> added new task <span class="noti-title">Patient appointment booking</span></p>
                  <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                </div>
                                  </div>
                              </a>
                          </li>
                          <li class="notification-message">
                              <a href="activities.html">
                                  <div class="media">
                <span class="avatar">V</span>
                <div class="media-body">
                  <p class="noti-details"><span class="noti-title">Tarah Shropshire</span> changed the task name <span class="noti-title">Appointment booking with payment gateway</span></p>
                  <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                </div>
                                  </div>
                              </a>
                          </li>
                          <li class="notification-message">
                              <a href="activities.html">
                                  <div class="media">
                <span class="avatar">G</span>
                <div class="media-body">
                  <p class="noti-details"><span class="noti-title">Rolland Webber</span> completed task <span class="noti-title">Patient and Doctor video conferencing</span></p>
                  <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                </div>
                                  </div>
                              </a>
                          </li>
                          <li class="notification-message">
                              <a href="activities.html">
                                  <div class="media">
                <span class="avatar">V</span>
                <div class="media-body">
                  <p class="noti-details"><span class="noti-title">Bernardo Galaviz</span> added new task <span class="noti-title">Private chat module</span></p>
                  <p class="noti-time"><span class="notification-time">2 days ago</span></p>
                </div>
                                  </div>
                              </a>
                          </li>
                      </ul>
                  </div>
                  <div class="topnav-dropdown-footer">
                      <a href="activities.html">View all Notifications</a>
                  </div>
              </div>
          </li>
          <li class="nav-item dropdown has-arrow">
            <%= link_to('Logout', destroy_user_session_path, class: "btn btn-danger", method: :delete) %>
          </li>
      </ul>

app/views/layouts/menu/_sidebar.html.erb
<% if staff_signed_in?%>
<div class="sidebar-inner slimscroll">
    <div id="sidebar-menu" class="sidebar-menu">
        <ul>
            <li class="menu-title">Main</li>
            <li class="active">
                <a href="index-2.html"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
            </li>
<li>
                <a href="doctors.html"><i class="fa fa-user-md"></i> <span>Doctors</span></a>
            </li>
            <li>
              <%= link_to patients_path do %>
                <i class="fa fa-wheelchair"></i> <span>Patients</span>
              <% end %>
            </li>
            <li>
                <a href="appointments.html"><i class="fa fa-calendar"></i> <span>Appointments</span></a>
            </li>
            <li>
                <a href="schedule.html"><i class="fa fa-calendar-check-o"></i> <span>Doctor Schedule</span></a>
            </li>
            <li>
                <a href="departments.html"><i class="fa fa-hospital-o"></i> <span>Departments</span></a>
            </li>
<li class="submenu">
  <a href="#"><i class="fa fa-user"></i> <span> Employees </span> <span class="menu-arrow"></span></a>
  <ul style="display: none;">
    <li>
      <%= link_to "Employees List", staffs_index_path %></li>
    <li><a href="leaves.html">Leaves</a></li>
    <li><a href="holidays.html">Holidays</a></li>
    <li><a href="attendance.html">Attendance</a></li>
  </ul>
</li>
<li class="submenu">
  <a href="#"><i class="fa fa-money"></i> <span> Accounts </span> <span class="menu-arrow"></span></a>
  <ul style="display: none;">
    <li><a href="invoices.html">Invoices</a></li>
    <li><a href="payments.html">Payments</a></li>
    <li><a href="expenses.html">Expenses</a></li>
    <li><a href="taxes.html">Taxes</a></li>
    <li><a href="provident-fund.html">Provident Fund</a></li>
  </ul>
</li>
<li class="submenu">
  <a href="#"><i class="fa fa-book"></i> <span> Payroll </span> <span class="menu-arrow"></span></a>
  <ul style="display: none;">
    <li><a href="salary.html"> Employee Salary </a></li>
    <li><a href="salary-view.html"> Payslip </a></li>
  </ul>
</li>
            <li>
                <a href="chat.html"><i class="fa fa-comments"></i> <span>Chat</span> <span class="badge badge-pill bg-primary float-right">5</span></a>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-video-camera camera"></i> <span> Calls</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="voice-call.html">Voice Call</a></li>
                    <li><a href="video-call.html">Video Call</a></li>
                    <li><a href="incoming-call.html">Incoming Call</a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-envelope"></i> <span> Email</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="compose.html">Compose Mail</a></li>
                    <li><a href="inbox.html">Inbox</a></li>
                    <li><a href="mail-view.html">Mail View</a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-commenting-o"></i> <span> Blog</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="blog-details.html">Blog View</a></li>
                    <li><a href="add-blog.html">Add Blog</a></li>
                    <li><a href="edit-blog.html">Edit Blog</a></li>
                </ul>
            </li>
<li>
  <a href="assets.html"><i class="fa fa-cube"></i> <span>Assets</span></a>
</li>
<li>
  <a href="activities.html"><i class="fa fa-bell-o"></i> <span>Activities</span></a>
</li>
<li class="submenu">
  <a href="#"><i class="fa fa-flag-o"></i> <span> Reports </span> <span class="menu-arrow"></span></a>
  <ul style="display: none;">
    <li><a href="expense-reports.html"> Expense Report </a></li>
    <li><a href="invoice-reports.html"> Invoice Report </a></li>
  </ul>
</li>
            <li>
                <a href="settings.html"><i class="fa fa-cog"></i> <span>Settings</span></a>
            </li>
            <li class="menu-title">UI Elements</li>
            <li class="submenu">
                <a href="#"><i class="fa fa-laptop"></i> <span> Components</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="uikit.html">UI Kit</a></li>
                    <li><a href="typography.html">Typography</a></li>
                    <li><a href="tabs.html">Tabs</a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-edit"></i> <span> Forms</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="form-basic-inputs.html">Basic Inputs</a></li>
                    <li><a href="form-input-groups.html">Input Groups</a></li>
                    <li><a href="form-horizontal.html">Horizontal Form</a></li>
                    <li><a href="form-vertical.html">Vertical Form</a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-table"></i> <span> Tables</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="tables-basic.html">Basic Tables</a></li>
                    <li><a href="tables-datatables.html">Data Table</a></li>
                </ul>
            </li>
            <li>
                <a href="calendar.html"><i class="fa fa-calendar"></i> <span>Calendar</span></a>
            </li>
            <li class="menu-title">Extras</li>
            <li class="submenu">
                <a href="#"><i class="fa fa-columns"></i> <span>Pages</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li><a href="login.html"> Login </a></li>
                    <li><a href="register.html"> Register </a></li>
                    <li><a href="forgot-password.html"> Forgot Password </a></li>
                    <li><a href="change-password2.html"> Change Password </a></li>
                    <li><a href="lock-screen.html"> Lock Screen </a></li>
                    <li><a href="profile.html"> Profile </a></li>
                    <li><a href="gallery.html"> Gallery </a></li>
                    <li><a href="error-404.html">404 Error </a></li>
                    <li><a href="error-500.html">500 Error </a></li>
                    <li><a href="blank-page.html"> Blank Page </a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="javascript:void(0);"><i class="fa fa-share-alt"></i> <span>Multi Level</span> <span class="menu-arrow"></span></a>
                <ul style="display: none;">
                    <li class="submenu">
                        <a href="javascript:void(0);"><span>Level 1</span> <span class="menu-arrow"></span></a>
                        <ul style="display: none;">
                            <li><a href="javascript:void(0);"><span>Level 2</span></a></li>
                            <li class="submenu">
                                <a href="javascript:void(0);"> <span> Level 2</span> <span class="menu-arrow"></span></a>
                                <ul style="display: none;">
                                    <li><a href="javascript:void(0);">Level 3</a></li>
                                    <li><a href="javascript:void(0);">Level 3</a></li>
                                </ul>
                            </li>
                            <li><a href="javascript:void(0);"><span>Level 2</span></a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><span>Level 1</span></a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<% end %>