config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    if Rails.env == "production"
        request.subdomain.present?
    elsif Rails.env == "staging"
      request.subdomain.present?
    else
      request.subdomain.present?
      end
  end
end

class SubdomainBlank
  def self.matches?(request)
    if Rails.env == "production"
        request.subdomain.blank?
    elsif Rails.env == "staging"
        request.subdomain.blank?
    else
        request.subdomain.blank?
    end
  end
end

Rails.application.routes.draw do


  get 'visits/create'
  get 'visits/update'
  get 'staffs/index'
  get 'staffs/new'
  get 'staffs/show'
  get 'staffs/edit'
  post 'create_staff', to: 'staffs#create_staff'
  # devise_for :users
  # constraints(SubdomainPresent) do
  #   root 'pages#subindex', as: :subdomain_root
  # end
  constraints(SubdomainBlank) do
    root 'pages#index'
  end

    devise_for :staffs, path: 'staffs', controllers: { sessions: "staffs/sessions", registrations: 'staffs/registrations', confirmations: 'staffs/confirmations', passwords: 'staffs/passwords', unlocks: 'staffs/unlocks'}
    devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations', confirmations: 'users/confirmations', passwords: 'users/passwords', unlocks: 'users/unlocks'}
  resources :staffs, :path_prefix => 'my'
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/edit'
  root 'pages#index'

  post 'create_visit', to: 'patients#create_visit'

  resources :patients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users
    resources :hospitals

  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  before_create :set_patient_num

  has_many :visits, dependent: :destroy
  jsonb_accessor :personal_details,
    patient_num: :string,
    patient_first_name: :string,
    patient_last_name: :string,
    phone_number: :string,
    address: :string,
    dob: :date

    validates :patient_num, uniqueness: true



    def generate_code(size=9)

      character_set = %w{ 0 1 2 3 4 5 6 7 8 9 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z}
      (0...9).map{ character_set.to_a[ rand(character_set.size) ] }.join
      
  end

  def set_patient_num
      self.patient_num = generate_code(9)
  end


end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_staff!, :set_patient, only: [:show]
  def index
    @patients = Patient.all
  end

  def show
    @visit = @patient.visits.new
    @visits = @patient.visits
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully added.' }
      else
        format.html { render :new }
      end
    end
  end

  def create_visit
    @patient = Patient.find(params[:visit][:patient_id])
    @visit = @patient.visits.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @patient, notice: 'Patient was successfully added.' }
      else
        format.html { render :show }
      end
    end
  end


  private
    def visit_params
      params.require(:visit).permit(:hospital_id, :patient_id, :diagnose_1, :diagnose_2, :diagnose_3, :diagnose_4, :diagnose_5, :diagnose_6, :treatment_on_site, :diagnose_on_site, :hemoglobin, :rbc, :htc, :mvc, :mch, :mchc, :rdw_cv, :rdw_sd, :wbc, :neuper, :granum, :plt, :esr, :symptoms_1, :symptoms_2, :symptoms_3, :symptoms_4, :symptoms_5, :symptoms_6, :prescription_1, :prescription_2, :prescription_3, :prescription_4, :prescription_5, :prescription_6 )
    end

    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:patient_first_name, :patient_num, :patient_last_name, :phone_number, :address, :dob)
    end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<div class="content">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
					<h4 class="page-title">Add Patient</h4>
				</div>
            </div>

				<div class="row">
				<div class="col-lg-8 offset-lg-2">

					<%= form_for @patient do |form| %>

						<div class="col-sm-6">
							<div class='form-group'>
								<%= form.label :patient_first_name %>
								<%= form.text_field :patient_first_name, class: 'form-control', placeholder: 'Enter Patients first name' %>
							</div>
						</div>

						  <div class="col-sm-6">
						<div class='form-group'>
						<%= form.label :patient_last_name%>
						<%= form.text_field :patient_last_name, class: 'form-control', placeholder: 'Enter Patients last name' %>
						</div>
						</div>

						<div class="col-sm-6">
						<div class='form-group'>
						<%= form.label :phone_number%>
						<%= form.text_field :phone_number, class: 'form-control', placeholder: 'Enter Patients Mobile number' %>
						</div>
						</div>

						<div class="col-sm-6">
						<div class='form-group'>
						<%= form.label:address%>
						<%= form.text_field :address, class: 'form-control', placeholder: 'Enter Patients home address' %>
						</div>
						</div>

						<div class="col-sm-4">
						<div class='form-group'>
						<%= form.label :dob%>
						<%= form.date_field :dob, class: 'form-control datetimepicker' %>
						</div>
						</div>

						<div class="m-t-20 text-center">
						<%= form.button :submit, class: 'btn btn-primary submit-btn' %>
						</div>
					<% end %>

				</div>
				</div>

				

</div>

app/views/patients/_visit.html.erb
<div class="content">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h4 class="page-title">Add Patient Visit Record</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <%= form_for @visit, url: create_visit_path do |form|%>
                <%= render 'shared/error_messages', object: @visit %>

                <h3>appointment</h3>
                <div class="col-sm-6">
                    <div class='form-group'>
                        <%= form.label :doctor_name %>
                        <%= form.text_field :doctor_name, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class='form-group'>
                        <%= form.label :appointment_time %>
                        <%= form.text_field :appointment_time, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
                    </div>
                </div>

                <h3>diagnose</h3>
                <div class="col-sm-6">
                <div class='form-group'>
                    <%= form.label :diagnose_on_site %>
                    <%= form.text_field :diagnose_on_site, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
                </div>
            </div>

            <div class="col-sm-6">
            <div class='form-group'>
                <%= form.label :treatment_on_site %>
                <%= form.text_field :treatment_on_site, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
            </div>
        </div>

        <div class="col-sm-6">
        <div class='form-group'>
            <%= form.label :diagnose_1%>
            <%= form.text_field :diagnose_1, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
        </div>
    </div>
    <div class="col-sm-6">
    <div class='form-group'>
        <%= form.label :diagnose_2%>
        <%= form.text_field :diagnose_2, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
    </div>
</div>
<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :diagnose_3%>
    <%= form.text_field :diagnose_4, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>
<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :diagnose_4%>
    <%= form.text_field :diagnose_4, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :diagnose_5%>
    <%= form.text_field :diagnose_5, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :diagnose_6%>
    <%= form.text_field :diagnose_6, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>


<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :diagnose_6%>
    <%= form.text_field :diagnose_6, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :diagnose_6%>
    <%= form.text_field :diagnose_6, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<h3>symptoms</h3>
<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :symptoms_1%>
    <%= form.text_field :symptoms_1, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :symptoms_2%>
    <%= form.text_field :symptoms_2, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :symptoms_3%>
    <%= form.text_field :symptoms_3, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :symptoms_4%>
    <%= form.text_field :symptoms_4, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :symptoms_5%>
    <%= form.text_field :symptoms_5, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :symptoms_6%>
    <%= form.text_field :symptoms_6, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

            
                

<h3>hemoglobin</h3>
<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :hemoglobin%>
    <%= form.text_field :hemoglobin, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :rbc%>
    <%= form.text_field :rbc, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :htc%>
    <%= form.text_field :htc, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :mvc%>
    <%= form.text_field :mvc, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :mch%>
    <%= form.text_field :mch, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :mchc%>
    <%= form.text_field :mchc, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :rdw_cv%>
    <%= form.text_field :rdw_cv, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :rdw_sd%>
    <%= form.text_field :rdw_sd, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :wbc%>
    <%= form.text_field :wbc, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :neuper%>
    <%= form.text_field :neuper, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :granum%>
    <%= form.text_field :granum, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :plt%>
    <%= form.text_field :plt, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>

<div class="col-sm-6">
<div class='form-group'>
    <%= form.label :esr%>
    <%= form.text_field :esr, class: 'form-control', placeholder: 'Enter Patients Diagnose on site' %>
</div>
</div>
<%= form.hidden_field :patient_id, value: @patient.id %>
<%= form.hidden_field :hospital_id, value: @hospital.id %>

<div class="m-t-20 text-center">
	<%= form.button :submit, class: 'btn btn-primary submit-btn' %>
</div>


            <% end %>
        </div>
    </div>


</div>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
<%= render 'form' %>

app/views/patients/index.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>


<div class="content">
<div class="row">
    <div class="col-sm-4 col-3">
        <h4 class="page-title">Patients</h4>
    </div>
    <div class="col-sm-8 col-9 text-right m-b-20">
		<a href="add-patient.html" class="btn btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Add Patient</a>
		<%= link_to 'Add Patient', patients_new_path %>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-border table-striped custom-table datatable mb-0">
                <thead>
					<tr>
						<th>Patient No.</th>
                        <th>First Name</th>
						<th>Last Name</th>
						<th>Phone</th>
						<th>Address</th>
						<th>DOB</th>
                        <th class="text-right">Action</th>
                    </tr>
                </thead>
				<tbody>
                    <% @patients.each do |p|%>
                    <tr>
                        <td><%= p.patient_num %></td>
                        <td><%= p.patient_first_name%></td>
                        <td><%= p.patient_last_name%></td>
                        <td><%= p.phone_number %></td>
                        <td><%= p.address%></td>
                        <td><%= p.dob%></td>
                        <td class="text-right">
                            <div class="dropdown dropdown-action">
                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
								<%= link_to 'show',p %>
								<a class="dropdown-item" href="edit-patient.html"><i class="fa fa-pencil m-r-5"></i> Edit</a>
								<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_patient"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                </div>
                            </div>
                        </td>
					</tr>
					<%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>

app/views/patients/new.html.erb
<h1>Edit Patient</h1>
<%= render 'form' %>

app/views/patients/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>

<p> <strong>Patient No.:</strong> <%= @patient.patient_num %></p>
<p> <strong>First Name:</strong> <%= @patient.patient_first_name %></p>
<p> <strong>Last Name:</strong> <%= @patient.patient_last_name %></p>
<p> <strong>Phone Number:</strong> <%= @patient.phone_number %></p>
<p> <strong> Address:</strong> <%= @patient.address %></p>
<p> <strong>D.O.B</strong> <%= @patient.dob %></p>



<h2>Visits</h2>

<%= render 'visit' %>


<div class="row">
    <div class="col-sm-4 col-3">
        <h4 class="page-title">Patients</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-border table-striped custom-table datatable mb-0">
                <thead>
					<tr>
						<th>Date</th>
                        <th>Hospital</th>
						<th>prescription</th>
						<th>lab results</th>
					
                        <th class="text-right">Action</th>
                    </tr>
                </thead>
				<tbody>
                    <% @visits.each do |p|%>
                    <tr>
                        <td><%= p.created_at %></td>
                        <td><%= hospital_name(p.hospital_id) %></td>
                        <td><%= p.diagnose %></td>
                        
                        <td><%= p.lab_results %></td>
                       
                        <td class="text-right">
                            <div class="dropdown dropdown-action">
                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-right">
								<a class="dropdown-item" href="edit-patient.html"><i class="fa fa-pencil m-r-5"></i> Edit</a>
								<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_patient"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                </div>
                            </div>
                        </td>
					</tr>
					<%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>